module Loremizer
  class << self
    
  @@lorem = 'Lorem ipsum dolor sit amet, dictum urna proin euismod ante, leo vivamus vestibulum vivamus nonummy augue, nec ipsum turpis massa et lectus, id sed sit. Pharetra phasellus nulla, nonummy sapien adipiscing urna ante eu augue. Augue etiam imperdiet at nulla lobortis, etiam aliquam ligula pariatur ultricies, placerat aptent vestibulum suspendisse dolor pede. Arcu a vulputate fusce, est conubia leo dignissim. Dictum vestibulum sed, nulla donec tellus eu hic, dignissim suspendisse eu nullam hendrerit. Mollis facilisis erat, vitae at egestas auctor mauris porta, luctus neque aliquam, libero ac iaculis dolor sed sed, pellentesque et dui. Urna in et tempor, phasellus purus. Vitae litora aliquam magna velit augue, placerat sed quisque mattis taciti nec, ultrices adipiscing sollicitudin, optio magna aenean integer. Ligula congue est sociosqu ante. Mauris cras libero sed, maecenas erat ut, quisque urna egestas faucibus fringilla tincidunt, nulla tincidunt. Mollis laoreet rhoncus nisl at quisque at, mauris pede eu mus velit commodo, gravida diam elit urna nibh turpis, tempor commodo dui elementum.
  Quis ligula luctus aliquet quam magnis, mauris porta consectetuer. In blandit mollis vehicula, justo dis, litora suscipit fringilla vitae, aenean pellentesque dolor suscipit nec, nunc eu ipsum. At ultrices lectus velit dis semper, quis nec morbi. Donec at felis nunc, amet massa. Pede pede urna metus qui aliquet, id vestibulum sed sed consectetur aliquam aptent, ipsum proin nec tempus arcu justo aliquam, wisi ut quam faucibus risus erat. Vivamus ligula dui non eget praesent, est aenean faucibus vestibulum urna vestibulum. Lorem et metus eget, rhoncus duis sociosqu urna nulla mi, dolorem ante ac. Commodo accumsan purus fermentum, libero vestibulum blandit, in lobortis morbi et at vehicula.
  Massa eget etiam sapien per, vel nibh nam orci, est quidem arcu. Felis vel, vivamus nulla netus vitae sociis et pulvinar, ante gravida libero metus nam diam, facilisis ante rutrum velit justo, integer magna. Orci fringilla rutrum diam. Mi sit id bibendum neque lorem leo, pellentesque pharetra aliquam, auctor eget lectus mi nulla, duis ac, lectus erat vestibulum bibendum leo. Nibh amet justo. Mauris aliquam ipsa sodales orci. Mi curabitur tellus nibh nec et, vel suscipit pede luctus suspendisse, montes est quam. Quisque vitae egestas est sed vitae nec, vestibulum ultrices odio pellentesque, pretium lectus mauris suscipit leo.
  Magna sociosqu scelerisque volutpat, turpis amet felis, sagittis tempor. Adipiscing vitae, arcu enim. Neque dui phasellus volutpat sit, aliquam tellus. Ligula nulla risus, enim eget sit eleifend hendrerit dictumst, dui elit et nulla potenti molestie. Faucibus volutpat a, ut eget est. Ac massa. Integer turpis amet, adipiscing tincidunt pellentesque condimentum, tempus wisi venenatis sit vitae. Nonummy cras, libero parturient consequat fames felis amet, ut velit, vulputate vestibulum eu interdum in.'
  
    def generate word_count = 25
        @@lorem.split.shuffle.slice(0..word_count).join(" ") 
    end
  end

end
